# Generated by Django 4.2.2 on 2023-08-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_rename_detallecursos_detallescursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fechaFinal',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 18, 59, 29, 92253)),
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 18, 59, 29, 92253)),
        ),
        migrations.AddField(
            model_name='cursos',
            name='horario',
            field=models.TextField(default='Lunes y Jueves de 19:00 a 21:00', max_length=100),
        ),
    ]
