# Generated by Django 4.2.2 on 2023-08-31 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cursos_fechafinal_cursos_fechainicio_cursos_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fechaFinal',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 19, 1, 20, 345446)),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 19, 1, 20, 345446)),
        ),
    ]
