# Generated by Django 4.2.2 on 2023-08-31 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursos_fechafinal_alter_cursos_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fechaFinal',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 17, 14, 34, 344093), verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 17, 14, 34, 344093), verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='horario',
            field=models.CharField(default='Lunes y Jueves de 19:00 a 21:00', max_length=100),
        ),
    ]
