# Generated by Django 4.2.2 on 2023-08-28 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 22, 8, 6, 282508)),
        ),
    ]
