# Generated by Django 4.2.2 on 2023-08-28 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_fecha_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 14, 29, 35, 124799)),
        ),
    ]
