# Generated by Django 4.2.2 on 2023-08-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_fecha_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 18, 59, 29, 90739)),
        ),
    ]
