# Generated by Django 4.2.2 on 2023-09-01 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_fecha_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_create',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 19, 40, 46, 743606)),
        ),
    ]
