# Generated by Django 4.2.2 on 2023-08-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('link', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clases')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
