# Generated by Django 4.2.2 on 2023-08-31 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 17, 14, 34, 418245)),
        ),
    ]
