# Generated by Django 4.2.2 on 2023-09-01 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 19, 40, 46, 816038)),
        ),
    ]
