# Generated by Django 4.2.2 on 2023-08-31 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_modulo_detallemodulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='curso',
        ),
    ]
